Namespace(gpu_id=0, dataset='ogbn-arxiv', dis_metric='ours', epochs=1000, nlayers=0, hidden=256, lr_adj=0.01, lr_feat=0.01, lr_model=0.01, weight_decay=0.0, dropout=0.5, normalize_features=True, keep_ratio=1.0, reduction_rate=0.005, seed=1, alpha=0, debug=0, sgc=1, inner=10, outer=20, save=1, model='GCN')
WARNING:root:The OGB package is out of date. Your version is 1.3.4, while the latest version is 1.3.5.
pyg_data: Data(num_nodes=169343, x=[169343, 128], node_year=[169343, 1], y=[169343, 1], adj_t=[169343, 169343, nnz=1166243])
split_index: {'train': tensor([     0,      1,      2,  ..., 169145, 169148, 169251]), 'valid': tensor([   349,    357,    366,  ..., 169185, 169261, 169296]), 'test': tensor([   346,    398,    451,  ..., 169340, 169341, 169342])}
train val test的长度: 90941 29799 48603
size of adj_train: (90941, 90941)
edges in adj_train: 738066.0
/home/xzb/GCond/gcond_agent_transduct.py:40: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /opt/conda/conda-bld/pytorch_1656352660876/work/torch/csrc/utils/tensor_new.cpp:201.)
  indices = torch.tensor([np.arange(n), np.arange(n)], dtype=torch.int64)
adj_syn: (439, 439) feat_syn: torch.Size([439, 128])
开始图凝聚！
epoch: 0
/home/xzb/anaconda3/envs/gd/lib/python3.9/site-packages/sklearn/manifold/_t_sne.py:800: FutureWarning: The default initialization in TSNE will change from 'random' to 'pca' in 1.2.
  warnings.warn(
/home/xzb/anaconda3/envs/gd/lib/python3.9/site-packages/sklearn/manifold/_t_sne.py:810: FutureWarning: The default learning rate in TSNE will change from 200.0 to 'auto' in 1.2.
  warnings.warn(
Epoch 0, 梯度匹配loss_avg: 34.39720703125
Traceback (most recent call last):
  File "/home/xzb/GCond/train_gcond_transduct.py", line 105, in <module>
    agent.train()
  File "/home/xzb/GCond/gcond_agent_transduct.py", line 230, in train
    res.append(self.test_with_val(data.feat_full, adj, best_acc))
  File "/home/xzb/GCond/gcond_agent_transduct.py", line 256, in test_with_val
    model.fit_with_val(args=args,features=feat_syn, adj=adj_syn, labels=labels_syn, data=data,train_iters=600, normalize=True, verbose=False, noval=True)
  File "/home/xzb/GCond/models/gcn.py", line 199, in fit_with_val
    self._train_with_val_perturbation(labels, data, train_iters, verbose, adj_val=noval)#pass syn labels
  File "/home/xzb/GCond/models/gcn.py", line 278, in _train_with_val_perturbation
    output = self.forward(self.features+perturb, self.adj_norm+perturb_adj)#use condensed graph and gcn to fit gcn
RuntimeError: add(sparse, dense) is not supported. Use add(dense, sparse) instead.
